"""
Finding and Evidence domain models.
High-precision forensic records linking security rule violations directly back to exact packet frame numbers,
timestamps, protocol layers, and observed values.
"""

import uuid
from datetime import datetime, timezone
from typing import TYPE_CHECKING, List, Optional
from sqlalchemy import DateTime, Enum, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.session import Base
from app.models.enums import Confidence, EvidenceStatus, FindingCategory, Severity

if TYPE_CHECKING:
    from app.models.capture import Capture
    from app.models.job import AnalysisJob
    from app.models.session import EmailSession



class Finding(Base):
    """
    Security finding generated by rule engine evaluation.
    """
    __tablename__ = "findings"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    job_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("analysis_jobs.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    session_id: Mapped[Optional[str]] = mapped_column(
        String(36),
        ForeignKey("email_sessions.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )

    rule_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    category: Mapped[FindingCategory] = mapped_column(
        Enum(FindingCategory), nullable=False
    )
    severity: Mapped[Severity] = mapped_column(
        Enum(Severity), nullable=False, index=True
    )
    confidence: Mapped[Confidence] = mapped_column(
        Enum(Confidence), nullable=False
    )
    status: Mapped[EvidenceStatus] = mapped_column(
        Enum(EvidenceStatus), nullable=False, default=EvidenceStatus.OBSERVED
    )

    score_contribution: Mapped[float] = mapped_column(
        Float, nullable=False, default=0.0
    )
    description: Mapped[str] = mapped_column(Text, nullable=False)
    remediation_recommendation: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    # ─── Relationships ────────────────────────────────────────────────────────
    job: Mapped["AnalysisJob"] = relationship("AnalysisJob", back_populates="findings")
    session: Mapped[Optional["EmailSession"]] = relationship(
        "EmailSession", back_populates="findings"
    )

    evidence: Mapped[List["Evidence"]] = relationship(
        "Evidence",
        back_populates="finding",
        cascade="all, delete-orphan",
        order_by="Evidence.frame_number",
    )


class Evidence(Base):
    """
    Critical forensic evidence record.
    Provides complete traceability from finding to exact PCAP frame, timestamp,
    protocol layer, and raw/parsed field observation.
    """
    __tablename__ = "evidence_records"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    finding_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("findings.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    capture_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("captures.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    session_id: Mapped[Optional[str]] = mapped_column(
        String(36),
        ForeignKey("email_sessions.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )

    frame_number: Mapped[int] = mapped_column(Integer, nullable=False, index=True)
    packet_timestamp: Mapped[float] = mapped_column(
        Float, nullable=False, index=True
    )  # Microsecond epoch timestamp
    protocol_layer: Mapped[str] = mapped_column(
        String(32), nullable=False
    )  # e.g., "ETH", "IP", "TCP", "SMTP", "TLS", "X509"
    field_name: Mapped[str] = mapped_column(String(128), nullable=False)
    observed_value: Mapped[str] = mapped_column(Text, nullable=False)
    source_reference: Mapped[Optional[str]] = mapped_column(
        String(255), nullable=True
    )

    evidence_status: Mapped[EvidenceStatus] = mapped_column(
        Enum(EvidenceStatus), nullable=False, default=EvidenceStatus.OBSERVED
    )
    hex_dump_snippet: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # ─── Relationships ────────────────────────────────────────────────────────
    finding: Mapped["Finding"] = relationship("Finding", back_populates="evidence")
    capture: Mapped["Capture"] = relationship("Capture")
    session: Mapped[Optional["EmailSession"]] = relationship("EmailSession")

